const announcements = [
    {
        id: "1",
        name: "Afonso Delgado",
        country: "Portugal",
        phone_number: "912345678",
        email: "afonsod@gmail.com",
        known_langs: { "Portuguese": "native", "English": "C1", "French": "B2" },
        lecture_langs: { "Portuguese": "native", "French": "B2" },
        description: "I am a teacher",
        certifications: ["zCambridge C1", "DELF B2", "DALF C1"],
        price: "10",
        rating: "4.8",
        reviews: "425",
        negotiable: true,
        profileimg: "http://www.utcswindon.co.uk/wp-content/uploads/2018/04/Ben.jpg",
        want_teach_to: ["Indiferent"],
    },
    {
        id: "2",
        name: "Maria Silva",
        country: "Portugal",
        phone_number: "943452428",
        email: "mariasilva@gmail.com",
        known_langs: { "Portuguese": "native", "Spanish": "A1", "English": "C1" },
        lecture_langs: { "English": "C1" },
        description: "Language Entusiast",
        certifications: ["Cambridge C1", "DELF A1"],
        price: "17",
        rating: "4.4",
        reviews: "96",
        negotiable: false,
        profileimg: "https://www.fairviewer.org/wp-content/uploads/2017/12/1Q01257.jpg",
        want_teach_to: ["Basic", "Intermediate"],
    },
    {
        id: "3",
        name: "Maria Silva",
        country: "Portugal",
        phone_number: "943452428",
        email: "mariasilva@gmail.com",
        known_langs: { "Portuguese": "native", "Spanish": "A1", "English": "C1" },
        lecture_langs: { "Spanish": "A1" },
        description: "Language Entusiast",
        certifications: ["Cambridge C1", "DELF A1"],
        price: "25",
        rating: "4.4",
        reviews: "96",
        negotiable: false,
        profileimg: "https://www.fairviewer.org/wp-content/uploads/2017/12/1Q01257.jpg",
        want_teach_to: ["Basic"],
    },
]

export default announcements;